### ISSUE TITLE
Fail to pull singularity image in HPC environment

### ISSUE THREAD

**Issue by DiegoBrambilla** [LNUc-EEMiS/metatdenovo-dsl1#10]
I am running `dev` reomtely in a HPC cluster.
Meaning, I do not have superuser authorization and I need to rely on singularity.

First, I load the singularity module with all dependencies:
```
$ module load autoload singularity/3.2.1
```
Then I try running the test case, but it fails because it is unable to access the singularity image
```
$ ./run_nextflow_test.sh
[...]
Error executing process > 'output_documentation'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name metatdenovo.simg.img docker://metatdenovo.simg > /dev/null
  status : 255
  message:
    [34mINFO:    Starting build...
    FATAL:   Unable to pull docker://metatdenovo.simg: conveyor failed to get: Error reading manifest latest in docker.io/library/metatdenovo.simg: errors:
    denied: requested access to the resource is denied
    unauthorized: authentication required
```
Even building the image through singularity is no good:
```
$ ./build_singularity.sh
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: Error loading image from docker engine: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Singularity runs normally after loading the modules, same for nextflow:
```
$ singularity version
3.2.1
$ nextflow -version

      N E X T F L O W
      version 20.04.1 build 5335
      created 03-05-2020 19:37 UTC (21:37 CEST)
      cite doi:10.1038/nbt.3820
      http://nextflow.io
```
I am not sure if the problem is related to my local HPC settings or the settings of the image.

**Comment by erikrikarddaniel** [comment]
The workflow is under development, so nobody built and uploaded an image anywhere, you'll have to do that yourself. There are scripts in the repo to do this. First you need to build a Docker image and, since you don't have root on the cluster, you'll have to do this on another computer where you have root access. It's probably easiest to build the singularity image there too so you don't have to upload the Docker image anywhere.
