### ISSUE TITLE
Process `get_software_versions` fails for trinity

### ISSUE THREAD

**Issue by emnilsson** [LNUc-EEMiS/metatdenovo-dsl1#19]
When running in a conda environment on macOS (10.14.6) the `get_software_versions` fails when trying to get the software version for trinity.

**Comment by erikrikarddaniel** [comment]
Trinity has a `--version` flag, but returns an exit code of 1 when run with that, which makes the process fail. That's why I resorted to the current "peeking into the script" solution. Can you, @emnilsson, try to run parts of the command to see where it fails for you?

**Comment by erikrikarddaniel** [comment]
Fixed in c4a1a3e
